main/urls.py
from django.urls import path
from . import views
from main.views import *
app_name = 'main'

urlpatterns = [

    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('characters/', views.character_list, name='character_list'),
    path('items/', views.item_list, name='item_list'),
    path('', show_main, name='show_main'),
    path('create-product', create_product, name='create_product'),
    path('create-character/', views.create_character, name='create_character'),
    path('create-item/', views.create_item, name='create_item'),
    path('xml/', show_xml, name='show_xml'), 
    path('json/', show_json, name='show_json'), 
    path('xml/character/<int:id>/', views.show_character_by_id_xml, name='show_character_by_id_xml'),
    path('xml/item/<int:id>/', views.show_item_by_id_xml, name='show_item_by_id_xml'),
    path('json/character/<int:id>/', views.show_character_by_id, name='show_character_by_id'),
    path('json/item/<int:id>/', views.show_item_by_id, name='show_item_by_id'),
    path('add_item/<int:item_id>/', views.add_item, name='add_item'),
    path('reduce_item/<int:item_id>/', views.reduce_item, name='reduce_item'),
    path('delete_item/<int:item_id>/', views.delete_item, name='delete_item'),
    path('create-item-ajax/', views.create_item_ajax, name='create_item_ajax'),
    path('create-character-ajax/', views.create_character_ajax, name='create_character_ajax'),
    path('get-item-json/', get_Item_json, name='get_item_json'),
    path('get-char-json/', get_Char_json, name='get_char_json'),
    path('delete-item-ajax/<int:id>', views.delete_item_ajax, name='delete_item_ajax'),





]

tugas2/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include


urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls)
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

class Character(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    level = models.IntegerField()
    # Atribut lain yang relevan dengan karakter

class Item(models.Model):
    name = models.CharField(max_length=255)
    amount = models.IntegerField()
    description = models.TextField()
    owner = models.ForeignKey(Character, on_delete=models.CASCADE, default=None, null=True)  # Menambahkan relasi dengan Character

    #Atribut lain yang relevan dengan item

class Product(models.Model):
    name = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

main/forms.py
from django.forms import ModelForm
from main.models import Product
from django import forms
from .models import Character, Item

class CharacterForm(forms.ModelForm):
    class Meta:
        model = Character
        fields = ['name', 'level']

from django.forms import ModelChoiceField

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['name', 'amount', 'description', 'owner']
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(ItemForm, self).__init__(*args, **kwargs)
        
        # Filter queryset karakter berdasarkan pengguna saat ini
        if user:
            self.fields['owner'].queryset = Character.objects.filter(user=user)

class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ["name", "price", "description"]

main/views.py
from django.shortcuts import render, get_object_or_404
from .models import Character, Item
from .forms import CharacterForm, ItemForm
from django.http import HttpResponseRedirect
import datetime, json
from main.forms import ProductForm
from main.models import Product
from django.urls import reverse
from django.http import HttpResponse, JsonResponse
from django.core import serializers
import xml.etree.ElementTree as ET
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages  
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse, HttpResponseNotFound

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
         login(request, user)
         response = HttpResponseRedirect(reverse("main:show_main")) 
         response.set_cookie('last_login', str(datetime.datetime.now()))
         return response
        else:
            messages.info(request, 'Sorry, incorrect username or password. Please try again.')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

def character_list(request):
    characters = Character.objects.all()
    return render(request, 'main/char_list.html', {'characters': characters})

def item_list(request):
    items = Item.objects.all()
    return render(request, 'main/item_list.html', {'items': items})

@login_required(login_url='/login')

def show_main(request):
    products = Product.objects.all()
    user = request.user  # Info pengguna saat ini
    username = request.user.username
    
    # Filter karakter yang dimiliki oleh pengguna saat ini menggunakan relasi 'owner'
    characters = Character.objects.filter(user=request.user)  # Mengambil karakter berdasarkan pengguna saat ini
    
    # Filter item yang dimiliki oleh pengguna saat ini menggunakan relasi 'owner'
    items = Item.objects.filter(owner__user=user)
    
    jumlah_character = characters.count()  # Menghitung jumlah karakter
    jumlah_item = items.count()  # Menghitung jumlah item

    last_login = request.COOKIES.get('last_login', 'Belum ada informasi login terakhir')  # Mengambil 'last_login' dari cookie atau default jika tidak ada

    context = {
        'username': username,
        'class': 'PBP B',  # Kelas PBP kamu
        'app_name': 'Equinos',
        'products': products,
        'characters': characters,
        'items': items,
        'jumlah_character': jumlah_character,  # Sertakan jumlah karakter dalam konteks
        'jumlah_item': jumlah_item, 
        'last_login': last_login,
    }

    return render(request, "main.html", context)

def create_product(request):
    form = ProductForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        form.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "create_product.html", context)

def show_xml(request):
    characters = Character.objects.all()
    items = Item.objects.all()

    # Menggabungkan daftar karakter dan daftar item
    data = list(characters) + list(items)

    # Mengonversi data menjadi XML
    xml_data = serializers.serialize("xml", data)

    return HttpResponse(xml_data, content_type="application/xml")

def show_json(request):
    characters = Character.objects.all()
    items = Item.objects.all()

    # Menggabungkan daftar karakter dan daftar item
    data = list(characters) + list(items)

    # Mengonversi data menjadi JSON
    json_data = serializers.serialize("json", data)

    return JsonResponse(json_data, safe=False)

def show_character_by_id_xml(request, id):
    character = get_object_or_404(Character, pk=id)
    
    # Membuat elemen XML untuk karakter
    character_element = ET.Element("Character")
    ET.SubElement(character_element, "Name").text = character.name
    ET.SubElement(character_element, "Level").text = str(character.level)
    
    # Membuat respons HTTP dengan konten tipe XML
    response = HttpResponse(content_type='application/xml')
    
    # Mengonversi elemen XML menjadi string dan menambahkannya ke respons
    character_tree = ET.ElementTree(character_element)
    character_tree.write(response, encoding='utf-8')
    
    return response

def show_item_by_id_xml(request, id):
    item = get_object_or_404(Item, pk=id)
    
    # Membuat elemen XML untuk item
    item_element = ET.Element("Item")
    ET.SubElement(item_element, "Name").text = item.name
    ET.SubElement(item_element, "Amount").text = str(item.amount)
    ET.SubElement(item_element, "Description").text = item.description
    
    # Jika item memiliki pemilik (owner), tambahkan informasi pemilik
    if item.owner:
        owner_element = ET.SubElement(item_element, "Owner")
        ET.SubElement(owner_element, "Name").text = item.owner.name
    
    # Membuat respons HTTP dengan konten tipe XML
    response = HttpResponse(content_type='application/xml')
    
    # Mengonversi elemen XML menjadi string dan menambahkannya ke respons
    item_tree = ET.ElementTree(item_element)
    item_tree.write(response, encoding='utf-8')
    
    return response

def show_character_by_id(request, id):
    character = get_object_or_404(Character, pk=id)
    # Mengonversi objek karakter menjadi JSON
    json_data = serializers.serialize("json", [character])
    return JsonResponse(json_data, safe=False)

def show_item_by_id(request, id):
    item = get_object_or_404(Item, pk=id)
    # Mengonversi objek item menjadi JSON
    json_data = serializers.serialize("json", [item])
    return JsonResponse(json_data, safe=False)

def create_character(request):
    if request.method == 'POST':
        character_form = CharacterForm(request.POST)
        if character_form.is_valid():
            character = character_form.save(commit=False)
            character.user = request.user  # Menyediakan pengguna yang terkait
            character.save()
            return redirect('main:show_main')
    else:
        character_form = CharacterForm()
    return render(request, "char_list.html", {'character_form': character_form})


def character_list(request):
    characters = Character.objects.filter(user=request.user)
    return render(request, 'char_list.html', {'characters': characters})

def create_item(request):
    error_message = ""
    
    if request.method == "POST":
        item_form = ItemForm(request.POST, user=request.user)

        if item_form.is_valid():
            item = item_form.save(commit=False)

            # Dapatkan karakter yang dipilih oleh pengguna melalui formulir
            selected_character = item_form.cleaned_data['owner']

            # Pastikan karakter tersebut dimiliki oleh pengguna saat ini
            if selected_character.user == request.user:
                item.owner = selected_character

                # Debug: Print item data
                print(item.name, item.amount, item.description, item.owner)

                item.save()
                return HttpResponseRedirect(reverse('main:show_main'))
            else:
                error_message = "Anda tidak memiliki izin untuk mengaitkan item dengan karakter ini."
        else:
            error_message = "Terdapat kesalahan dalam formulir, silakan periksa kembali."
    else:
        item_form = ItemForm()
    
    characters = Character.objects.filter(user=request.user)
    context = {'item_form': item_form, 'characters': characters, 'error_message': error_message}
    return render(request, "item_list.html", context)

def get_items(request):
    items = Item.objects.all()  # Gantilah sesuai dengan model Item Anda
    item_data = []

    for item in items:
        item_data.append({
            'name': item.name,
            'amount': item.amount,
            'description': item.description,
            'owner': item.owner.name if item.owner else None,  # Jika ada pemilik, gunakan nama pemilik, jika tidak, None
        })

    return JsonResponse({'items': item_data})

def add_item(request, item_id):
    item = get_object_or_404(Item, pk=item_id)
    if item.amount > 0:
        item.amount += 1
        item.save()
    return HttpResponseRedirect(reverse('main:show_main'))

def reduce_item(request, item_id):
    item = get_object_or_404(Item, pk=item_id)
    if item.amount > 0:
        item.amount -= 1
        item.save()
    return HttpResponseRedirect(reverse('main:show_main'))

def delete_item(request, item_id):
    item = get_object_or_404(Item, pk=item_id)
    item.delete()
    return HttpResponseRedirect(reverse('main:show_main'))

def get_Item_json(request):
    product_item = Item.objects.all()
    return HttpResponse(serializers.serialize('json', product_item))

def get_Char_json(request):
    char_list = Character.objects.all()
    return HttpResponse(serializers.serialize('json', char_list))


@csrf_exempt  # mematikan proteksi CSRF; gunakan dengan hati-hati!
def create_item_ajax(request):    
    if request.method == "POST":
        item_form = ItemForm(request.POST, user=request.user)
        print(item_form.is_valid())
        if item_form.is_valid():

main/templates/create_product.html
{% extends 'base.html' %} 

{% block content %}
<h1>Add New Product</h1>

<form method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Add Product"/>
            </td>
        </tr>
    </table>
</form>

{% endblock %}

main/templates/item_list.html
<!-- item_list.html -->
<div class="container">
    <h2 class="text-center mb-5">Item List</h2>
    <div class="row">
        {% for item in items %}
            <div class="col-md-4">
                <div class="card mb-4">
                    <img src="{{ item.image.url }}" class="card-img-top" alt="{{ item.name }}">
                    <div class="card-body">
                        <h5 class="card-title">{{ item.name }}</h5>
                        <p class="card-text">{{ item.description }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <form method="post" action="{% url 'main:add_item' item.id %}">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-success">Tambah</button>
                            </form>
                            <form method="post" action="{% url 'main:reduce_item' item.id %}">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-warning">Kurang</button>
                            </form>
                            <form method="post" action="{% url 'main:delete_item' item.id %}">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-danger">Hapus</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

    <h2 class="mt-5">Create New Item</h2>
    <div class="card">
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ item_form.as_p }}
                <button type="submit" class="btn btn-primary mt-3">Create Item</button>
            </form>
        </div>
    </div>
</div>

main/templates/login.html
{% extends 'base.html' %}

{% block meta %}
    <title>Login</title>
{% endblock meta %}

{% block content %}
<style>
/* CSS untuk halaman login */
.login {
    max-width: 400px;
    margin: 0 auto;
    padding: 20px;
    background-color: #f4f4f4;
    border-radius: 5px;
    box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
    text-align: center;
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
}

.login h1 {
    text-align: center;
    font-size: 20px;
    margin-bottom: 20px;
    color: #333;
}

.login table {
    width: 100%;
}

.login .form-control {
    width: 100%;
    padding: 10px;
    border: 1px solid #ccc;
    border-radius: 5px;
    margin-bottom: 10px;
    text-align: center;
}

.login .login_btn {
    background-color: #007bff;
    color: #fff;
    text-align: center;
    border: none;
    border-radius: 10px;
    padding: 6px 20px;
    cursor: pointer;
}

.login .login_btn:hover {
    background-color: #0056b3;
}

.login .message {
    margin-top: 7px;
    color: red;
}

.login a {
    font-size: 14px;
    text-decoration: none;
    color: #007bff;
}

.login a:hover {
    text-decoration: underline;
}
</style>

<div class="login">

    <h1>Login</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td>Username: </td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>
                    
            <tr>
                <td>Password: </td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>

            <tr>
                <td></td>
                <td><input class="btn login_btn" type="submit" value="Login"></td>
            </tr>
        </table>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li class="message">{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
        
    Don't have an account yet? <a href="{% url 'main:register' %}">Register Now</a>

</div>

{% endblock content %}

main/templates/main.html
{% extends 'base.html' %}

{% block extra_head %}
  <style>
    /* Add hover effect to table rows */
    .table-characters tbody tr:hover,
    .table-items tbody tr:hover {
      background-color: #f5f5f5;
    }

    /* Gaya untuk baris terakhir tabel karakter */
    .table-characters tbody tr:last-child {
      background-color: #90EE90; /* hijau muda */
      color: #8B0000; /* merah tua */
    }

    /* Gaya untuk baris terakhir tabel item */
    .table-items tbody tr:last-child {
      background-color: #FFD700; /* emas */
      color: #4B0082; /* ungu */
    }
  </style>
{% endblock %}

{% block content %}
    <div class="container">
        <!-- <h1 class="text-center" style="color: #ff9900;">Equinos Data Centre</h1>

        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header">
                        <h5 class="card-title" style="color: #666;">Username:</h5>
                    </div>
                    <div class="card-body">
                        <p class="card-text">{{ username }}</p>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header">
                        <h5 class="card-title" style="color: #666;">Class:</h5>
                    </div>
                    <div class="card-body">
                        <p class="card-text">{{ class }}</p>
                    </div>
                </div>
            </div> -->
        <!-- </div> -->

        <!-- Tabel Karakter -->
        <!-- <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">
                        <h2 class="card-title" style="color: #666;">Character List</h2>
                    </div>
                    <div class="card-body">
                        <p class="card-text">Kamu memiliki {{ jumlah_character }} karakter pada aplikasi ini.</p>
                        <table class="table table-bordered table-hover table-characters">
                            <thead class="thead-dark">
                                <tr>
                                    <th scope="col">Name</th>
                                    <th scope="col">Level</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for character in characters %}
                                <tr>
                                    <td>{{ character.name }}</td>
                                    <td>{{ character.level }}</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                        <a href="{% url 'main:create_character' %}" class="btn btn-primary" style="margin-top: 10px;">Add New Character</a>
                    </div>
                </div>
            </div>
        </div> -->

        
<!-- Form Create Item -->
<!-- <div class="row justify-content-center">
    <div class="col-md-8">
        <div class="card">
            <div class="card-header">
                <h2 class="card-title" style="color: #666;">Create New Item</h2>
            </div>
            <div class="card-body">
                <form id="addItemForm", onsubmit="return false;">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="name" class="col-form-label">Name:</label>
                        <input type="text" class="form-control" id="name" name="name">
                    </div>
                    <div class="mb-3">
                        <label for="amount" class="col-form-label">Amount:</label>
                        <input type="number" class="form-control" id="price" name="price">
                    </div>
                    <div class="mb-3">
                        <label for="description" class="col-form-label">Description:</label>
                        <textarea class="form-control" id="description" name="description"></textarea>
                    </div>
                    <div class="mb-3">
                        <label for="character" class="col-form-label">Character:</label>
                        <select class="form-control" id="character" name="character">
                            {% for character in characters %}
                                <option value="{{ character.id }}">{{ character.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary" id="addItemBtn">Add Item</button>
                    </div>
                </form>
            </div>
            
        </div>
    </div>
</div> -->

        <!-- Item List -->
        <!-- <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">
                        <h2 class="card-title" style="color: #666;">Item List</h2>
                    </div>
                    <div class="card-body">
                        <p class="card-text">Kamu menyimpan {{ jumlah_item }} jenis item pada aplikasi ini.</p>
                        <table id="product_table"></table>
                    </div>
                </div>
            </div>
        </div> -->

        <h5 class="text-center" style="color: #666; margin-top: 20px;">Sesi terakhir login: {{ last_login }}</h5>

        <!-- Tombol Logout -->
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-body">
                        <a href="{% url 'main:logout' %}" class="btn btn-danger" style="margin-top: 20px;">Logout</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<table id="character_table"></table>
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">Add Character by AJAX</button>
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Add New Product</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="form" onsubmit="return false;">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="name" class="col-form-label">Name:</label>
                        <input type="text" class="form-control" id="name" name="name"></input>
                    </div>
                    <div class="mb-3">
                        <label for="level" class="col-form-label">Level:</label>
                        <input type="number" class="form-control" id="level" name="level"></input>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="button_add_char" data-bs-dismiss="modal">Add Product</button>
            </div>
        </div>
    </div>
</div>


<table id="product_table"></table>
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">Add Item by AJAX</button>
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Add New Product</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="form" onsubmit="return false;">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="name" class="col-form-label">Name:</label>
                        <input type="text" class="form-control" id="name" name="name">
                    </div>
                    <div class="mb-3">
                        <label for="amount" class="col-form-label">Amount:</label>
                        <input type="number" class="form-control" id="amount" name="amount">
                    </div>
                    <div class="mb-3">
                        <label for="description" class="col-form-label">Description:</label>
                        <textarea class="form-control" id="description" name="description"></textarea>
                    </div>
                    <div class="mb-3">
                        <label for="character" class="col-form-label">Character:</label>
                        <select class="form-control" id="owner" name="owner">
                            {% for character in characters %}
                                <option value="{{ character.id }}">{{ character.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="button_add" data-bs-dismiss="modal">Add Product</button>
            </div>
        </div>
    </div>
</div>
<script>
    async function getItem() {
        return fetch("{% url 'main:get_item_json' %}").then((res) => res.json())
    }
    async function getChar() {
        return fetch("{% url 'main:get_char_json' %}").then((res) => res.json())
    }
    
    async function refreshItems() {
        document.getElementById("product_table").innerHTML = ""
        const products = await getItem()
        let htmlString = `<tr>
            <th>Name</th>
            <th>Amount</th>
            <th>Description</th>
            <th>Owner</th>
            <th> Delete </th>
        </tr>`
        products.forEach((item) => {
            htmlString += `\n<tr>
            <td>${item.fields.name}</td>
            <td>${item.fields.amount}</td>
            <td>${item.fields.description}</td>
            <td>${item.fields.owner}</td>
            <td><button type="button" class="btn btn-danger" onclick="deleteItemAJAX(${item.pk})">Delete</button></td>
        </tr>` 
        })
        
        document.getElementById("product_table").innerHTML = htmlString
    }

    refreshItems()

    function addItem() {
        fetch("{% url 'main:create_item_ajax' %}", {
            method: "POST",
            body: new FormData(document.querySelector('#form'))
        }).then(refreshItems)

        document.getElementById("form").reset()
        return false
    }
    document.getElementById("button_add").onclick = addItem

    async function refreshCharacter() {
        document.getElementById("character_table").innerHTML = ""
        const products = await getChar()
        let htmlString = `<tr>
            <th>Name</th>
            <th>Level</th>
            
        </tr>`
        products.forEach((character) => {
            htmlString += `\n<tr>
            <td>${character.fields.name}</td>
            <td>${character.fields.level}</td>
        </tr>` 
        })
        
        document.getElementById("character_table").innerHTML = htmlString
    }

    refreshCharacter()

    function addChar() {
        fetch("{% url 'main:create_character_ajax' %}", {
            method: "POST",
            body: new FormData(document.querySelector('#form'))
        }).then(refreshItems)

        document.getElementById("form").reset()
        return false
    }
    document.getElementById("button_add_char").onclick = addChar

    function deleteItemAJAX(id){
        fetch(`/delete-item-ajax/${id}`, {
            method: "POST",
        
        }).then(refreshItems)

        document.getElementById("form").reset()
        return false
    }
</script>
{% endblock content %}